Categoryid
JaqKent/cuervodelnorte-frontend pull request #11
Opened 2022-07-13 02:06 UTC by JaqKent

implementation of the category of each product and the fix of the modal bug

2022-07-13 02:36 UTC, nathan-hyan requested changes
Outstanding job

2022-07-13 02:36 UTC, nathan-hyan commented on src/components/CustomModal/styles.module.scss
> +  min-width: 100%;
Sort css alphabetically

2022-07-13 02:36 UTC, nathan-hyan commented on src/App/App.tsx
>  import Footer from "components/Footer/index";
Sort imports

2022-07-13 02:36 UTC, nathan-hyan commented on src/components/ProductScreen/index.tsx
> +  const { id } = useParams<any>();
Replace any for string

2022-07-13 02:36 UTC, nathan-hyan commented on src/components/productCard/styles.module.scss
> +    width: 300px;
Sort css

2022-07-13 02:36 UTC, nathan-hyan commented on src/components/productCategory/styles.module.scss
>      color: $white;
Sort css

2022-07-15 00:21 UTC, JaqKent commented on src/components/CustomModal/styles.module.scss
> +  min-width: 100%;
done

2022-07-15 00:28 UTC, JaqKent commented on src/App/App.tsx
>  import Footer from "components/Footer/index";
done

2022-07-15 00:29 UTC, JaqKent commented on src/components/ProductScreen/index.tsx
> +  const { id } = useParams<any>();
done

2022-07-15 00:32 UTC, JaqKent commented on src/components/productCard/styles.module.scss
> +    width: 300px;
done

2022-07-15 00:37 UTC, JaqKent commented on src/components/productCategory/styles.module.scss
>      color: $white;
done

2022-07-15 00:37 UTC, merged