searchBar-implementation
JaqKent/cuervodelnorte-frontend pull request #15
Opened 2022-07-29 02:00 UTC by JaqKent

funcionality of the search bar...part 1

2022-07-29 09:55 UTC, nathan-hyan requested changes
Great job, some comments

2022-07-29 09:55 UTC, nathan-hyan commented on src/components/searchBar/index.tsx
> +import { useContext, useState } from "react";
React goes first always

2022-07-29 09:55 UTC, nathan-hyan commented on src/components/searchBar/index.tsx
> +  const onChange = (event: any) => {
Don't any

2022-08-03 03:38 UTC, JaqKent commented on src/components/searchBar/index.tsx
> +import { useContext, useState } from "react";
done

2022-08-03 03:38 UTC, JaqKent commented on src/components/searchBar/index.tsx
> +  const onChange = (event: any) => {
done

2022-08-03 12:22 UTC, nathan-hyan requested changes
Two comments left

2022-08-03 12:22 UTC, nathan-hyan commented on src/components/searchBar/index.tsx
> +    console.log("search", searchItem);
Console log

2022-08-03 12:22 UTC, nathan-hyan commented on src/components/searchBar/index.tsx
> +            {" "}
Remove this space if it isnt necessary

2022-08-18 23:22 UTC, merged